%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-jsk-rqt-plugins
Version:        2.1.7
Release:        4%{?dist}%{?release_suffix}
Summary:        ROS jsk_rqt_plugins package

License:        BSD
URL:            http://jsk-docs.readthedocs.io/en/latest/jsk_visualization/doc/jsk_rqt_plugins
Source0:        %{name}-%{version}.tar.gz

Requires:       python3-scikit-learn
Requires:       ros-noetic-cv-bridge
Requires:       ros-noetic-image-publisher >= 1.12.23
Requires:       ros-noetic-image-view2
Requires:       ros-noetic-jsk-gui-msgs >= 4.3.0
Requires:       ros-noetic-message-runtime
Requires:       ros-noetic-qt-gui-py-common
Requires:       ros-noetic-resource-retriever
Requires:       ros-noetic-rqt-gui
Requires:       ros-noetic-rqt-gui-py
Requires:       ros-noetic-rqt-image-view
Requires:       ros-noetic-rqt-plot
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-image-view2
BuildRequires:  ros-noetic-message-generation
BuildRequires:  ros-noetic-mk
BuildRequires:  ros-noetic-rosbuild
BuildRequires:  ros-noetic-roslaunch
BuildRequires:  ros-noetic-rostest
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The jsk_rqt_plugins package

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Oct 27 2020 Ryohei Ueda <ueda@jsk.t.u-tokyo.ac.jp> - 2.1.7-4
- Autogenerated by Bloom

